/* ============================================================
   Watsons & Co — Property Data
   ============================================================ */

const PROPERTIES = [

  // ── For Sale ──────────────────────────────────────────────

  {
    id: 'jesmond-villa',
    status: 'sale',
    tag: 'For Sale',
    isNew: false,
    price: '£1,150,000',
    priceNum: 1150000,
    name: 'Edwardian Villa',
    area: 'Jesmond',
    location: 'Jesmond, Newcastle NE2',
    beds: 5,
    baths: 3,
    sqft: 3800,
    img: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=560&fit=crop',
    imgs: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&h=800&fit=crop',
    ],
    description: [
      'A magnificent Edwardian villa occupying a prime position on one of Jesmond\'s most sought-after streets. Presented to an exceptional standard throughout, this substantial family home retains an abundance of original period features including ornate cornicing, original fireplaces, and beautifully restored sash windows.',
      'The generous accommodation is arranged over three floors and comprises a grand entrance hall, dual-aspect drawing room, formal dining room, bespoke kitchen/breakfast room opening onto the garden, five bedrooms and three bathrooms. To the rear, a beautifully landscaped walled garden provides a private and tranquil outdoor sanctuary.',
    ],
    features: [
      'Five bedrooms, three bathrooms',
      'Bespoke hand-crafted kitchen',
      'Dual-aspect drawing room with original fireplace',
      'Walled south-facing rear garden',
      'Original period features throughout',
      'Off-street parking for two vehicles',
      'Gas central heating',
      'Moments from Jesmond Metro station',
    ],
    epc: 'D', tenure: 'Freehold', council: 'Newcastle City Council',
  },

  {
    id: 'northumberland-manor',
    status: 'sale',
    tag: 'For Sale',
    isNew: true,
    price: '£2,750,000',
    priceNum: 2750000,
    name: 'Northumberland Manor',
    area: 'Northumberland',
    location: 'Corbridge, Northumberland',
    beds: 8,
    baths: 6,
    sqft: 11200,
    img: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=560&fit=crop',
    imgs: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1200&h=800&fit=crop',
    ],
    description: [
      'An exceptional Grade II listed manor house set in approximately 12 acres of formal gardens and grounds in one of Northumberland\'s most picturesque villages. This magnificent property, dating from the late 18th century, has been sympathetically restored and extended to provide outstanding modern family accommodation while retaining all of its original grandeur.',
      'The principal rooms are elegantly proportioned and include a magnificent entrance hall, four reception rooms, a superb kitchen and entertaining space, and a self-contained cottage ideal for guests or staff. The grounds include formal parterre gardens, a walled kitchen garden, and paddocks.',
    ],
    features: [
      'Grade II Listed, circa 1780',
      'Approximately 12 acres of grounds',
      'Four principal reception rooms',
      'Bespoke kitchen and entertaining space',
      'Self-contained guest cottage',
      'Walled kitchen garden and paddocks',
      'Triple garage with room above',
      'Within 8 miles of Newcastle city centre',
    ],
    epc: 'E', tenure: 'Freehold', council: 'Northumberland County Council',
  },

  {
    id: 'contemporary-ponteland',
    status: 'sale',
    tag: 'For Sale',
    isNew: false,
    price: '£1,450,000',
    priceNum: 1450000,
    name: 'Contemporary Residence',
    area: 'Ponteland',
    location: 'Ponteland, NE20',
    beds: 5,
    baths: 4,
    sqft: 4600,
    img: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=560&fit=crop',
    imgs: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1200&h=800&fit=crop',
    ],
    description: [
      'An architecturally stunning contemporary residence in the heart of Ponteland village, designed and built to the very highest specification. Floor-to-ceiling glazing floods the interior with natural light, whilst seamlessly connecting the living spaces to the beautifully landscaped garden beyond.',
      'The property offers an exceptional open-plan kitchen, dining and living space, a dedicated home office, cinema room, and five luxurious bedroom suites. The principal suite features a walk-in wardrobe and a freestanding bath with garden views. Smart home automation throughout.',
    ],
    features: [
      'Architect-designed contemporary build',
      'Open-plan kitchen, dining and living',
      'Principal suite with walk-in wardrobe',
      'Dedicated home office and cinema room',
      'Underfloor heating throughout',
      'Smart home automation system',
      'Professionally landscaped rear garden',
      'Double garage with EV charging point',
    ],
    epc: 'B', tenure: 'Freehold', council: 'Northumberland County Council',
  },

  {
    id: 'victorian-townhouse-gosforth',
    status: 'sale',
    tag: 'For Sale',
    isNew: true,
    price: '£895,000',
    priceNum: 895000,
    name: 'Victorian Townhouse',
    area: 'Gosforth',
    location: 'Gosforth, Newcastle NE3',
    beds: 4,
    baths: 3,
    sqft: 2800,
    img: 'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&h=560&fit=crop',
    imgs: [
      'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1200&h=800&fit=crop',
    ],
    description: [
      'A beautifully presented Victorian townhouse in a prime Gosforth location, extensively renovated to combine period character with contemporary comfort. The property sits on a generous plot with a private rear garden and benefits from off-street parking to the front.',
      'The interior has been thoughtfully designed, retaining original cornicing, ceiling roses and fireplaces whilst incorporating a stunning bespoke kitchen and luxuriously appointed bathrooms. An ideal family home moments from Gosforth High Street and excellent local schools.',
    ],
    features: [
      'Extensively renovated period townhouse',
      'Bespoke Neptune kitchen',
      'En-suite principal bedroom',
      'Private rear garden',
      'Off-street parking',
      'Close to Gosforth High Street',
      'Highly regarded school catchment',
      'Within 3 miles of Newcastle city centre',
    ],
    epc: 'D', tenure: 'Freehold', council: 'Newcastle City Council',
  },

  {
    id: 'heaton-terrace',
    status: 'sale',
    tag: 'For Sale',
    isNew: false,
    price: '£575,000',
    priceNum: 575000,
    name: 'Period Terrace',
    area: 'Heaton',
    location: 'Heaton, Newcastle NE6',
    beds: 4,
    baths: 2,
    sqft: 2200,
    img: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=560&fit=crop',
    imgs: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=1200&h=800&fit=crop',
    ],
    description: [
      'A superbly renovated Victorian terrace in the ever-popular Heaton neighbourhood, offering the perfect blend of period elegance and modern convenience. Sympathetically updated by its current owners, the property retains many fine original features including bay windows, fireplaces, and decorative cornicing.',
      'Arranged over three floors, the well-planned accommodation includes four bedrooms, two bathrooms, a wonderful open-plan kitchen/dining room to the rear, and a comfortable sitting room. A private courtyard garden completes this excellent family home.',
    ],
    features: [
      'Renovated Victorian terrace',
      'Open-plan kitchen and dining room',
      'Four bedrooms, two bathrooms',
      'Private rear courtyard garden',
      'Original fireplaces and bay windows',
      'Gas central heating',
      'Close to Heaton Park',
      'Excellent transport links',
    ],
    epc: 'D', tenure: 'Freehold', council: 'Newcastle City Council',
  },

  {
    id: 'sandyford-semi',
    status: 'sale',
    tag: 'For Sale',
    isNew: false,
    price: '£420,000',
    priceNum: 420000,
    name: 'Sandyford Semi-Detached',
    area: 'Sandyford',
    location: 'Sandyford, Newcastle NE2',
    beds: 3,
    baths: 2,
    sqft: 1500,
    img: 'https://images.unsplash.com/photo-1512917774080-9b274b97b72f?w=800&h=560&fit=crop',
    imgs: [
      'https://images.unsplash.com/photo-1512917774080-9b274b97b72f?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&h=800&fit=crop',
    ],
    description: [
      'A charming and well-presented Edwardian semi-detached house in the highly sought-after Sandyford area, moments from Jesmond and the city centre. Offering flexible and bright accommodation, the property benefits from a lovely private garden and retains many original features.',
      'Ideal for first-time buyers, young professionals or small families, this is a wonderful opportunity to acquire a well-maintained home in one of Newcastle\'s most central and convenient locations, with excellent nearby amenities and public transport.',
    ],
    features: [
      'Well-presented Edwardian semi',
      'Three bedrooms',
      'Modern fitted kitchen',
      'Private rear garden',
      'Off-street parking',
      'Original period features',
      'Moments from Jesmond',
      'Excellent transport links',
    ],
    epc: 'D', tenure: 'Freehold', council: 'Newcastle City Council',
  },

  // ── To Let ────────────────────────────────────────────────

  {
    id: 'quayside-apartment',
    status: 'let',
    tag: 'To Let',
    isNew: false,
    price: '£2,800 pcm',
    priceNum: 2800,
    name: 'Quayside Apartment',
    area: 'Quayside',
    location: 'Quayside, Newcastle NE1',
    beds: 2,
    baths: 2,
    sqft: 1200,
    img: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=560&fit=crop',
    imgs: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1200&h=800&fit=crop',
    ],
    description: [
      'An outstanding two-bedroom apartment in one of Newcastle\'s most prestigious riverside developments, offering spectacular views across the Tyne. Presented in immaculate condition and available immediately, the apartment provides sophisticated city living at its finest.',
      'The interior is finished to an exceptional specification throughout, with a fully equipped open-plan kitchen, two double bedrooms both with en-suite facilities, and a generous balcony from which to enjoy the river views. Secure underground parking and a concierge service complete this outstanding offering.',
    ],
    features: [
      'Spectacular Tyne River views',
      'Both bedrooms with en-suite bathrooms',
      'Private balcony',
      'Secure underground parking',
      'Concierge building service',
      'Residents\' gym and lounge',
      'Available immediately',
      'Unfurnished or part-furnished',
    ],
    epc: 'B', tenure: 'Leasehold', council: 'Newcastle City Council',
  },

  {
    id: 'tyne-view-penthouse',
    status: 'let',
    tag: 'To Let',
    isNew: false,
    price: '£3,500 pcm',
    priceNum: 3500,
    name: 'Tyne View Penthouse',
    area: 'Quayside',
    location: 'Quayside, Newcastle NE1',
    beds: 3,
    baths: 2,
    sqft: 1800,
    img: 'https://images.unsplash.com/photo-1512917774080-9b274b97b72f?w=800&h=560&fit=crop',
    imgs: [
      'https://images.unsplash.com/photo-1512917774080-9b274b97b72f?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=1200&h=800&fit=crop',
    ],
    description: [
      'A truly exceptional penthouse apartment positioned on the top floor of one of the Quayside\'s finest buildings, offering panoramic views of the Tyne bridges and the city skyline. Occupying approximately 1,800 square feet, this is without question one of the finest rental properties in the city.',
      'The penthouse features a stunning wraparound terrace, a statement open-plan living space, three double bedrooms, and a principal suite of exceptional quality with dressing room. Available furnished or unfurnished, this property must be seen to be fully appreciated.',
    ],
    features: [
      'Penthouse level with wraparound terrace',
      'Panoramic Tyne bridge views',
      'Three double bedrooms',
      'Principal suite with dressing room',
      'Statement open-plan living and dining',
      'Two secure parking spaces',
      'Premium concierge building',
      'Available furnished or unfurnished',
    ],
    epc: 'B', tenure: 'Leasehold', council: 'Newcastle City Council',
  },

  {
    id: 'jesmond-garden-flat',
    status: 'let',
    tag: 'To Let',
    isNew: true,
    price: '£1,600 pcm',
    priceNum: 1600,
    name: 'Jesmond Garden Apartment',
    area: 'Jesmond',
    location: 'Jesmond, Newcastle NE2',
    beds: 2,
    baths: 1,
    sqft: 900,
    img: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=560&fit=crop',
    imgs: [
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&h=800&fit=crop',
    ],
    description: [
      'A charming two-bedroom garden apartment in the heart of Jesmond, one of Newcastle\'s most desirable residential areas. Beautifully presented throughout, the apartment benefits from its own private patio garden — a true rarity in this location.',
      'The interior is light and airy, with a well-equipped kitchen, two comfortable double bedrooms, a stylish bathroom, and a bright living room with direct garden access. Close to Jesmond\'s excellent cafés, restaurants and Metro station.',
    ],
    features: [
      'Ground floor with private patio garden',
      'Two double bedrooms',
      'Stylish fully fitted kitchen',
      'Light and airy living room',
      'Close to Jesmond Metro station',
      'Local cafés and restaurants nearby',
      'Available immediately',
      'Pets considered',
    ],
    epc: 'C', tenure: 'Leasehold', council: 'Newcastle City Council',
  },

  {
    id: 'gosforth-cottage',
    status: 'let',
    tag: 'To Let',
    isNew: false,
    price: '£1,950 pcm',
    priceNum: 1950,
    name: 'Gosforth Cottage',
    area: 'Gosforth',
    location: 'Gosforth, Newcastle NE3',
    beds: 3,
    baths: 2,
    sqft: 1600,
    img: 'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&h=560&fit=crop',
    imgs: [
      'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&h=800&fit=crop',
    ],
    description: [
      'A delightful three-bedroom detached cottage in the heart of Gosforth, available for immediate occupancy. Full of charm and character, this wonderful property offers spacious and flexible accommodation in one of Newcastle\'s most sought-after residential suburbs.',
      'The ground floor features a well-equipped kitchen, a comfortable sitting room with original fireplace, and a separate dining room. Three well-proportioned bedrooms and two bathrooms occupy the upper floor, alongside a private enclosed rear garden perfect for families.',
    ],
    features: [
      'Charming detached cottage',
      'Original fireplace in sitting room',
      'Three bedrooms, two bathrooms',
      'Private enclosed rear garden',
      'Off-street parking',
      'Close to Gosforth High Street',
      'Excellent school catchment',
      'Available immediately',
    ],
    epc: 'C', tenure: 'Leasehold', council: 'Newcastle City Council',
  },

];
